### ISSUE TITLE
decision on non-functional/functional requirements

### ISSUE THREAD

**Issue by filipamarta** [holisticon/atomic-playfulness#16]
do a meeting with all the team + sponsor to:

- discuss non-functional requirements (accessibility, performance, etc) and have a decision about MUST, SHOULD, COULD and WON'T DO (create a ADR doc for these decisions). 
- Think about what we need to do to achieve these non-functional requirements
- discuss functional requirements 
- make a decision
- install what is needed to proceed

**Comment by mrm1st3r** [comment]
results are documented at: https://github.com/holisticon/atomic-playfulness/blob/main/docs/10_quality_requirements.md
