### ISSUE TITLE
Rework the textfield into a more flexible input element.

### ISSUE THREAD

**Issue by filipamarta** [holisticon/atomic-playfulness#35]
- don't use only one css class for the input as a whole, but mutliple classes for individual parts to be more flexible
- improve UI

**Comment by MarioBiehs** [comment]
@christoph-fricke Es gibt ja jetzt zum Textfield eine ausgearbeitete Komponente mit allen Varianten. Soll die hier beschrieben werden oder soll ich dafür ein neues Ticket aufmachen?

**Comment by mrm1st3r** [comment]
there will be another ticket for the textfield.
